services:
  build_container:
    image: deskhop-build
    build:
      context: .
    volumes:
      - ..:/deskhop:z
  build_container_privileged:
    image: deskhop-build
    build:
      context: .
    volumes:
      - ..:/deskhop:z
    privileged: true
