
#!/bin/bash

dd if=/dev/zero of=fat.img bs=2M count=1

mkdosfs  -F12 -n DESKHOP -i 0 fat.img

sudo mount -o loop,x-mount.mkdir -t vfat fat.img /mnt/disk/
sudo cp ../webconfig/config.htm /mnt/disk/config.htm

# Create a placeholder CONFIG.INI (~4KB) so its directory entry and cluster
# allocation are present in the disk image. Actual content is generated at runtime.
python3 -c "
content = '# DeskHop configuration file\n# This file is automatically generated from device config on mount.\n# Edit and save to update device settings.\n'
print(content + ' ' * (4096 - len(content)), end='')" > /tmp/config_placeholder.ini
sudo cp /tmp/config_placeholder.ini /mnt/disk/CONFIG.INI

sudo umount /mnt/disk

dd if=fat.img of=disk.img bs=512 count=128
rm fat.img
